<?php

namespace Shift\ShiftBundle\Repository\Shift;

/**
 * fysShiftApplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fysShiftApplyRepository extends \Doctrine\ORM\EntityRepository
{
}
