<?php

namespace Shift\ShiftBundle\Repository\Shift;

/**
 * FysShiftAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FysShiftAlertRepository extends \Doctrine\ORM\EntityRepository
{
}
