<?php

namespace Shift\ShiftBundle\Repository\Shift;

/**
 * ShiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNot($status)
    {
        $qb = $this->createQueryBuilder('s')
        ->where('s.shiftStatus != :status')
        ->setParameter('status', $status)
        ->orderBy('s.id', 'desc')
        ->getQuery();
        return $qb->getResult();
    }
}
