<?php

namespace Shift\ShiftBundle\Repository\Event;

/**
 * EventMetaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventMetaDataRepository extends \Doctrine\ORM\EntityRepository
{
}
