<?php

namespace Shift\ShiftBundle\Repository\Event;

/**
 * FysEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FysEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
