employer_add:
    path: /employer/add
    defaults: { _controller: EmployerBundle:Employer:add }
employer_update:
    path: /employer/update/{id}
    defaults: { _controller: EmployerBundle:Employer:update }
employer_get:
    path: /employer/get/{id}
    defaults: { _controller: EmployerBundle:Employer:get }