employer_add:
    path: /employer/add
    defaults: { _controller: EmployerBundle:Employer:add }
employer_update:
    path: /employer/update/{id}
    defaults: { _controller: EmployerBundle:Employer:update }
