<?php

namespace Shift\ShiftBundle\Repository\User;

/**
 * FysEmployeeResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FysEmployeeResumeRepository extends \Doctrine\ORM\EntityRepository
{
}
