<?php

namespace Shift\ShiftBundle\Repository\User;

/**
 * fysEmployeeResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fysEmployeeResumeRepository extends \Doctrine\ORM\EntityRepository
{
}
