<?php

namespace Shift\ShiftBundle\Repository\User;

/**
 * FysEmployeeResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FysEmployeeResumeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByEmployeeId($employeeID)
    {
        $resumeDetails = $this->createQueryBuilder('e')
            ->where('e.employeeId = :employeeID')
            ->setParameter('employeeID', $employeeID)
            ->getQuery()->getResult();
        if (empty($resumeDetails)){
            return [];
        }
        return $resumeDetails[0];
    }
}
