<?php

namespace Shift\ShiftBundle\Repository\User;

/**
 * fysUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fysUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function setUserDetails(){
        
    }
}
