<?php

namespace Shift\ShiftBundle\Repository\User;

/**
 * FysUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FysUserRepository extends \Doctrine\ORM\EntityRepository
{
//    public function setUserDetails()
//    {
//
//    }
}
