shift_homepage:
    path:     /
    defaults: { _controller: ShiftBundle:Shift:index }
dashboard:
    path: /dashboard
    defaults: {_controller: ShiftBundle:Shift:dashboard}
add:
    path:     user/add
    defaults: { _controller: ShiftBundle:ShiftUser:add }

update:
    path:     /user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }

get:
    path:     /user/get/{id}
    defaults: { _controller: ShiftBundle:ShiftUser:get }

get:
    path:     /user/get
    defaults: { _controller: ShiftBundle:ShiftUser:get }

update:
    path:    /user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }

get:
    path:     /user/get
    defaults: { _controller: ShiftBundle:ShiftUser:get }

delete:
    path:     /user/delete
    defaults: { _controller: ShiftBundle:ShiftUser:delete }

update:
    path:     /user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }
    
register:
    path:     /user/register
    defaults: { _controller: ShiftBundle:ShiftUser:register }
login:
    path:     /user/login/social
    defaults: { _controller: ShiftBundle:User:login }

save_extra:
    path:     /user/login/social/save
    defaults: { _controller: ShiftBundle:User:saveExtraDetails }
google:
    path:     /user/google
    defaults: { _controller: ShiftBundle:ShiftUser:loginWithGoogle }

google_redirect:
    path:     /user/google/redirect
    defaults: { _controller: ShiftBundle:User:redirectWithGoogle }

createShift:
    path: /shift/create
    defaults: { _controller: ShiftBundle:Shift:createNewShift }

submitShift:
    path: /shift/submit
    defaults: { _controller: ShiftBundle:Shift:submitShift }
    
viewShift:
    path: /shift/view/{id}
    defaults: { _controller: ShiftBundle:Shift:viewShift }
    
deleteShift:
    path: /shift/delete/{id}
    defaults: { _controller: ShiftBundle:Shift:deleteShift }
    
listShifts:
    path: /shift/list
    defaults: { _controller: ShiftBundle:Shift:listShifts }
    
publishShift:
    path: /shift/publish/{id}
    defaults: { _controller: ShiftBundle:Shift:publishShift } 
updateShift:
    path: /shift/update/{id}
    defaults: { _controller: ShiftBundle:Shift:updateShift }
saveShift:
    path: /shift/save/{id}
    defaults: { _controller: ShiftBundle:Shift:saveShift }
subscribeShift:
    path: /shift/subscribe/{id}
    defaults: { _controller: ShiftBundle:Shift:subscribeShift }
unsubscribeShift:
    path: /shift/unsubscribe/{id}
    defaults: { _controller: ShiftBundle:Shift:unsubscribeShift }
approveShift:
    path: /shift/approve/{id}/{subscriberId}
    defaults: { _controller: ShiftBundle:Shift:approveShift }
employeeViewShift:
    path: /shift/eview/{id}
    defaults: { _controller: ShiftBundle:Shift:employeeViewShift }
acceptShift:
    path: /shift/accept/{id}
    defaults: { _controller: ShiftBundle:Shift:acceptShift }
checkInShift:
    path: /shift/checkin/{id}
    defaults: { _controller: ShiftBundle:Shift:checkInShift }
completeShift:
    path: /shift/complete/{id}
    defaults: { _controller: ShiftBundle:Shift:completeShift }
rejectShift:
    path: /shift/reject/{id}
    defaults: { _controller: ShiftBundle:Shift:rejectShift }