shift_homepage:
    path:     /
    defaults: { _controller: ShiftBundle:Shift:index }
dashboard:
    path: /dashboard
    defaults: {_controller: ShiftBundle:Shift:dashboard}
add:
    path:     user/add
    defaults: { _controller: ShiftBundle:ShiftUser:add }

update:
    path:     /user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }

get:
    path:     /user/get/{id}
    defaults: { _controller: ShiftBundle:ShiftUser:get }

get:
    path:     /user/get
    defaults: { _controller: ShiftBundle:ShiftUser:get }

update:
    path:     user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }

get:
    path:     /user/get
    defaults: { _controller: ShiftBundle:ShiftUser:get }

delete:
    path:     /user/delete
    defaults: { _controller: ShiftBundle:ShiftUser:delete }

update:
    path:     /user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }

add:
    path:     /user/add
    defaults: { _controller: ShiftBundle:ShiftUser:add }

login:
    path:     /user/login
    defaults: { _controller: ShiftBundle:ShiftUser:login }

createShift:
    path: /shift/create
    defaults: { _controller: ShiftBundle:Shift:createNewShift }

submitShift:
    path: /shift/submit
    defaults: { _controller: ShiftBundle:Shift:submitShift }
    
viewShift:
    path: /shift/view/{id}
    defaults: { _controller: ShiftBundle:Shift:viewShift }
    
deleteShift:
    path: /shift/delete/{id}
    defaults: { _controller: ShiftBundle:Shift:deleteShift }
    
listShifts:
    path: /shift/list
    defaults: { _controller: ShiftBundle:Shift:listShifts }