shift_homepage:
    path:     /
    defaults: { _controller: ShiftBundle:Shift:index }
dashboard:
    path: /dashboard
    defaults: {_controller: ShiftBundle:Shift:dashboard}
add:
    path:     user/add
    defaults: { _controller: ShiftBundle:ShiftUser:add }
profile:
  path:     /user/profile
  defaults: { _controller: ShiftBundle:ShiftUser:profile }
finish_profile:
  path:     /user/profile/finish
  defaults: { _controller: ShiftBundle:ShiftUser:finishProfile }
ajax_personal_profile:
  path:     /user/profile/personal
  defaults: { _controller: ShiftBundle:ShiftUser:savePersonal }
ajax_address_details:
  path:     /user/profile/address
  defaults: { _controller: ShiftBundle:ShiftUser:saveAddressDetails }
ajax_more_info:
  path:     /user/profile/more
  defaults: { _controller: ShiftBundle:ShiftUser:saveEmployeeMore }
ajax_resume:
  path:     /user/profile/resume
  defaults: { _controller: ShiftBundle:ShiftUser:saveEmployeeResume }
update:
    path:     /user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }

get:
    path:     /user/get/{id}
    defaults: { _controller: ShiftBundle:ShiftUser:get }

get:
    path:     /user/get
    defaults: { _controller: ShiftBundle:ShiftUser:get }

update:
    path:    /user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }

get:
    path:     /user/get
    defaults: { _controller: ShiftBundle:ShiftUser:get }

delete:
    path:     /user/delete
    defaults: { _controller: ShiftBundle:ShiftUser:delete }

update:
    path:     /user/update
    defaults: { _controller: ShiftBundle:ShiftUser:update }
    
register:
    path:     /user/register
    defaults: { _controller: ShiftBundle:ShiftUser:register }
login:
    path:     /user/login/social
    defaults: { _controller: ShiftBundle:User:login }

save_extra:
    path:     /user/login/social/save
    defaults: { _controller: ShiftBundle:User:saveExtraDetails }
google:
    path:     /user/google
    defaults: { _controller: ShiftBundle:ShiftUser:loginWithGoogle }

google_redirect:
    path:     /user/google/redirect
    defaults: { _controller: ShiftBundle:User:redirectWithGoogle }

facebook:
    path:     /user/facebook
    defaults: { _controller: ShiftBundle:User:loginWithFacebook }

facebook_redirect:
    path:     /user/facebook/redirect
    defaults: { _controller: ShiftBundle:User:redirectWithFaceBook }

employerShiftFlow:
  path:     /employer/shiftFlow/{id}
  defaults: { _controller: ShiftBundle:Employer:employerShiftFlow }
createShift:
    path: /employer/create
    defaults: { _controller: ShiftBundle:Employer:createNewShift }

submitShift:
    path: /employer/submit
    defaults: { _controller: ShiftBundle:Employer:submitShift }
    
viewShift:
    path: /employer/view/{id}
    defaults: { _controller: ShiftBundle:Employer:viewShift }
    
deleteShift:
    path: /employer/delete/{id}
    defaults: { _controller: ShiftBundle:Employer:deleteShift }
    
employerListShifts:
    path: /employer/list
    defaults: { _controller: ShiftBundle:Employer:listShifts }
    
publishShift:
    path: /employer/publish/{id}
    defaults: { _controller: ShiftBundle:Employer:publishShift }
    
updateShift:
    path: /employer/update/{id}
    defaults: { _controller: ShiftBundle:Employer:updateShift }
    
saveShift:
    path: /employer/save/{id}
    defaults: { _controller: ShiftBundle:Employer:saveShift }
    
approveShift:
    path: /employer/approve/{id}/{subscriberId}
    defaults: { _controller: ShiftBundle:Employer:approveShift } 

employeeViewShift:
    path: /employee/view/{id}
    defaults: { _controller: ShiftBundle:Employee:employeeViewShift }  

employeeListShifts:
    path: /employee/list
    defaults: { _controller: ShiftBundle:Employee:listShifts }
    
subscribeShift:
    path: /employee/subscribe/{id}
    defaults: { _controller: ShiftBundle:Employee:subscribeShift }

unsubscribeShift:
    path: /employee/unsubscribe/{id}
    defaults: { _controller: ShiftBundle:Employee:unsubscribeShift }
 
acceptShift:
    path: /employee/accept/{id}
    defaults: { _controller: ShiftBundle:Employee:acceptShift }
checkInShift:
    path: /employee/checkin/{id}
    defaults: { _controller: ShiftBundle:Employee:checkInShift }
completeShift:
    path: /employee/complete/{id}
    defaults: { _controller: ShiftBundle:Employee:completeShift }
rejectShift:
    path: /employee/reject/{id}
    defaults: { _controller: ShiftBundle:Employee:rejectShift }