services:
 login.valid.user:
   class: Shift\ShiftBundle\Services\LoginAsValidUser
   arguments:
     - '@service_container'

 fys.genericEvent:
   class: Shift\ShiftBundle\Services\FYSLogEvent
   arguments:
     - '@service_container'
     - '@doctrine.orm.entity_manager'

 user.resume.completeness:
    class: Shift\ShiftBundle\Services\UserResumeCompletenessManager
