services:
 login.valid.user:
   class: Shift\ShiftBundle\Services\LoginAsValidUser
   arguments:
     - '@service_container'

 fys.genericEvent:
   class: Shift\ShiftBundle\Services\FYSLogEvent
   arguments:
     - '@service_container'
     - '@doctrine.orm.entity_manager'
#    shift.example:
#        class: Shift\ShiftBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
