shift:
    resource: "@ShiftBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: '.'
    type:     'api_platform'
   
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

