shift:
    resource: "@ShiftBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: '.'
    type:     'api_platform'
   
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_security_login:
    path:      /user/login
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }
