shift:
    resource: "@ShiftBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: '.'
    type:     'api_platform'
   
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security_login:
    path:      /user/login
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

fos_user_security_check:
    path:      /user/login_check
    defaults:  { _controller: FOSUserBundle:Security:check, _method: POST }
#hwi auth integration settings
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

github_login:
    path: /connect/check-github

facebook_login:
    path: /connect/check-facebook

googleplus_login:
    path: /connect/check-googleplus

stackexchange_login:
    path: /connect/check-stackexchange
