# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /user/login_check
                login_path: /user/login/social
                csrf_parameter:       _csrf_token
                csrf_token_id:        authenticate
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path:            dashboard
                use_referer:                    true

            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
            oauth:
                            # Declare the OAuth Callback URLs for every resource owner
                            # They will be added in the routing.yml file too later
              resource_owners:
#               github: "/connect/check-github"
                facebook: "/connect/check-facebook"
                googleplus: "/connect/check-googleplus"
#               stackexchange: "/connect/check-stackexchange"
                ## Provide the original login path of your application (fosuserroute)
                ## and the failure route when the authentication fails.
              login_path:     /user/login
              failure_path:   /user/login
                            # Inject a service that will be created in the step #6
              oauth_user_provider:
                service: app.fos_user.oauth_provider
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/dashboard, role: ROLE_USER }
