<?php

namespace Shift\ShiftBundle\Repository;

/**
 * FysRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FysRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
