<?php

namespace Shift\ShiftBundle\Repository;

/**
 * fysRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fysRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
