<?php

namespace Shift\ShiftBundle\Repository;

/**
 * FysRoleEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FysRoleEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
