<?php

namespace Shift\ShiftBundle\Repository\Org;

/**
 * SectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorRepository extends \Doctrine\ORM\EntityRepository
{
}
