<?php

namespace Shift\ShiftBundle\Repository\Admin;

/**
 * DisputeSettlementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisputeSettlementRepository extends \Doctrine\ORM\EntityRepository
{
}
