<?php

namespace Shift\ShiftBundle\Repository\Admin;

/**
 * NoShowRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoShowRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
